import type { Metadata } from "next";
import "./globals.css";
import NavBar from '../components/NavBar'; // Import the NavBar component
import Head from "next/head"; // Head component for meta tags

export const metadata: Metadata = {
  title: "SnapZoska", // Title for the webpage
  description: "Generated by students of SPSE Zochova 9, Bratislava", // Description for the webpage
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // TypeScript type for children prop
}>) {
  return (
    <html lang="sk">
      <Head>
        <link rel="icon" href="/favicon.ico" /> {/* Favicon */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" /> {/* Responsive design */}
      </Head>
      <body>
        <div style={{ paddingBottom: "56px", minHeight: "100vh" }}> {/* Ensure content is not hidden behind the navbar */}
          {children} {/* Render child components */}
          <NavBar /> {/* Add the NavBar component here */}
        </div>
      </body>
    </html>
  );
}
